[package]
name = "ddns"
version = "0.1.0"
authors = ["jarryliu <jarrysix@gmail.com>"]
edition = "2018"

[dependencies]
sys-info = "*"
reqwest = "*"
regex = "~1"
clap = "~2.32"
serde = "~1.0"
serde_json = "~1.0"
serde_derive = "~1.0"